.TH PLAINFETCH 1 "2026-08-26" "plainfetch" "User Commands"

.SH NAME
plainfetch \- display GNU/Linux system information

.SH SYNOPSIS
.B plainfetch

.SH DESCRIPTION
Plainfetch is a minimal fetch script written in POSIX sh. 
Plainfetch is very minimal by default.
Users can modify the logo to their liking by modifying the
.I logo
file. 

.SH FILES

.TP
.I logo
Used to display a four-line ASCII logo.

.SH EXAMPLES
.nf
plainfetch
.fi

.SH LICENSE
Plainfetch is licensed under the MIT License. The default logo is licensed under the following terms:

Copyright © 2004 Martin Dickopp

Permission is given to copy or distribute (or both) the above ASCII image, with or without modifications.
